-- data_report table schema (dynamic readings per day)
-- Generated on 2025-12-24

CREATE TABLE IF NOT EXISTS `data_report` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(64) NOT NULL,
  `event` VARCHAR(128) NULL,
  `date` DATE NULL,
  `actual_on_time` DATE NULL,
  `actual_off_time` DATE NULL,
  `r_volt` DECIMAL(10,3) NULL,
  `y_volt` DECIMAL(10,3) NULL,
  `b_volt` DECIMAL(10,3) NULL,
  `r_cur` DECIMAL(10,3) NULL,
  `y_cur` DECIMAL(10,3) NULL,
  `b_cur` DECIMAL(10,3) NULL,
  `r_kw` DECIMAL(10,3) NULL,
  `y_kw` DECIMAL(10,3) NULL,
  `b_kw` DECIMAL(10,3) NULL,
  `r_pf` DECIMAL(10,3) NULL,
  `y_pf` DECIMAL(10,3) NULL,
  `b_pf` DECIMAL(10,3) NULL,
  `battery_status` DECIMAL(10,3) NULL,
  `battery_backup_hrs` DECIMAL(10,3) NULL,
  `day_open_reading` DECIMAL(12,3) NULL,
  `day_close_reading` DECIMAL(12,3) NULL,
  `cur_reading` DECIMAL(12,3) NULL,
  `baseline_kWh` DECIMAL(12,3) NULL,
  `adjusted_baseline_kWh` DECIMAL(12,3) NULL,
  `actual_consumption_kWh` DECIMAL(12,3) NULL,
  `energy_saved_kWh` DECIMAL(12,3) NULL,
  `energy_saving_per` DECIMAL(7,3) NULL,
  `lamp_burning_per` DECIMAL(7,3) NULL,
  `status` VARCHAR(64) NULL,
  `CCMS_STATUS` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_data_report_uid_date` (`uid`, `date`),
  CONSTRAINT `fk_data_report_uid_status` FOREIGN KEY (`uid`) REFERENCES `status` (`uid`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
